#!/bin/sh

# Copyright (c) 2016-2018 The Flint OS Authors. All rights reserved.
# Distributed under the terms of the GNU General Public License v2

UI_MACHINE_INFO_FILE=/run/session_manager/machine-info
OEM_PATH=/usr/share/oem
STORED_MAC_FILE=$OEM_PATH/.vpd_info
NET_NODE=/sys/class/net
LAN_MAC_NODE=$NET_NODE/eth0/address
WLAN_MAC_NODE=$NET_NODE/wlan0/address

# Just continue if one of the commands below fails.
#set +e

get_serial(){
     	grep '"serial_number"' $UI_MACHINE_INFO_FILE |sed 's/"serial_number"=//g'|sed 's/"//g'|sed '/^$/d'
}

get_system_mac(){
	if [ -e $LAN_MAC_NODE ]; then
		cat $LAN_MAC_NODE
	elif [ -e $WLAN_MAC_NODE ]; then
		cat $WLAN_MAC_NODE
	else
		ifconfig -a | awk '/ether/ {print $2;exit}'
	fi 
}

remount_root_writable(){
	mount -o remount rw /
}

remount_root_readonly(){
	mount -o remount ro /
}

remount_oem_writable(){
	mount -o remount,rw "$OEM_PATH"
}

remount_oem_readonly(){
	mount -o remount,ro "$OEM_PATH"
}

store_mac(){
	local mac=$1
	local oem_mounted
	if mount | grep -q $OEM_PATH; then
		oem_mounted="oem_mounted"
	fi
	if [ ! -z "$mac" ]; then
		if [ ! -z "$oem_mounted" ]; then
			remount_oem_writable
		else
			remount_root_writable
		fi
		echo $mac > $STORED_MAC_FILE
		chmod 400 $STORED_MAC_FILE
		if [ ! -z "$oem_mounted" ]; then
			remount_oem_readonly
		else
			remount_root_readonly
		fi
	fi
}

get_mac(){
	if [ -e $STORED_MAC_FILE ]; then
		cat $STORED_MAC_FILE
	else
		local mac=$(get_system_mac)
		echo $mac
		store_mac $mac
	fi
}
# serial number and echo group code.
system_serial=$(get_serial)
if [ ! -z "$system_serial" ]; then 
	exit 0
fi
serial=$(get_mac | sed "s/://g")
if [ ! -z "$serial" ]; then
	echo "\"serial_number\"=\"${serial}\"" >> "${UI_MACHINE_INFO_FILE}"
fi
